:toc: right
:backend: html5
:doctitle: Living Documentation
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 1

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Automated-User-Acceptance-Tests-for-the-Sentiment-Analysis-Application>>*
|4
|0
|4
|22
|0
|0
|0
|0
|0
|22
|23s 416ms
|[green]#*passed*#
12+^|*Totals*
|4|0|4|22|0|0|0|0|0|22 2+|23s 416ms
|===

== *Features*

[[Automated-User-Acceptance-Tests-for-the-Sentiment-Analysis-Application, Automated User Acceptance Tests for the Sentiment Analysis Application]]
=== *Automated User Acceptance Tests for the Sentiment Analysis Application*

ifndef::backend-pdf[]
minmax::Automated-User-Acceptance-Tests-for-the-Sentiment-Analysis-Application[]
endif::[]
==== Background

==========
Given ::
Open https://fhvweatherapp.herokuapp.com/ icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 383ms)#
==========

==== Scenario: Test login and logout

==========
Given ::
Login with user 'user@test.com' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 375ms)#
When ::
I press logout icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 100ms)#
Then ::
I see the login page icon:thumbs-up[role="green",title="Passed"] [small right]#(164ms)#
==========

==== Scenario: Test real location

==========
Given ::
Login with user 'user@test.com' icon:thumbs-up[role="green",title="Passed"] [small right]#(936ms)#
When ::
Check the weather 'Dornbirn' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 299ms)#
Then ::
The Location should be Dornbirn icon:thumbs-up[role="green",title="Passed"] [small right]#(707ms)#
And ::
I press logout icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 547ms)#
==========

==== Scenario: Test unknown location

==========
Given ::
Login with user 'user@test.com' icon:thumbs-up[role="green",title="Passed"] [small right]#(852ms)#
When ::
Check the weather 'asdf1234' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 253ms)#
Then ::
The Weather should be City not found icon:thumbs-up[role="green",title="Passed"] [small right]#(723ms)#
And ::
I press logout icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 517ms)#
==========

==== Scenario: User interaction with history (video)

==========
Given ::
Login with user 'user2@test.com' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 032ms)#
When ::
Check the weather 'Dornbirn' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 286ms)#
When ::
Check the weather 'Bregenz' icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 282ms)#
And ::
Navigate to history icon:thumbs-up[role="green",title="Passed"] [small right]#(566ms)#
Then ::
The 1. row shows the history item with text 'Dornbirn' has weatherinformations icon:thumbs-up[role="green",title="Passed"] [small right]#(538ms)#
And ::
The 2. row shows the history item with text 'Bregenz' has weatherinformations icon:thumbs-up[role="green",title="Passed"] [small right]#(549ms)#
And ::
I press logout icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 590ms)#
==========

